// Documentation: https://developers.google.com/fonts/docs/material_symbols

/** @enum {String} */
export default {
  account_tree: 'account_tree',
  article: 'article',
  arrow_back: 'arrow_back',
  arrow_drop_down: 'arrow_drop_down',
  arrow_forward: 'arrow_forward',
  chevron_left: 'chevron_left',
  chevron_right: 'chevron_right',
  class: 'class',
  close: 'close',
  code: 'code',
  content_copy: 'content_copy',
  dashboard: 'dashboard',
  data_object: 'data_object',
  database: 'database',
  delete: 'delete',
  description: 'description',
  dns: 'dns',
  center_focus_strong: 'center_focus_strong',
  edit: 'edit',
  expand_less: 'expand_less',
  expand_more: 'expand_more',
  folder: 'folder',
  fullscreen: 'fullscreen',
  fullscreen_exit: 'fullscreen_exit',
  functions: 'functions',
  gesture: 'gesture',
  home: 'home',
  hub: 'hub',
  input: 'input',
  link: 'link',
  login: 'login',
  logout: 'logout',
  map: 'map',
  memory: 'memory',
  open_in_new: 'open_in_new',
  output: 'output',
  package_2: 'package_2',
  person: 'person',
  play_arrow: 'play_arrow',
  precision_manufacturing: 'precision_manufacturing',
  radio_button_checked: 'radio_button_checked',
  route: 'route',
  search: 'search',
  sell: 'sell',
  settings: 'settings',
  touch_app: 'touch_app',
  trending_flat: 'trending_flat',
  tune: 'tune',
  visibility: 'visibility',
  visibility_off: 'visibility_off',
  web_asset: 'web_asset',
  work: 'work',
};
