import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';
import test from 'node:test';

import { PORTFOLIO_LOCALE_MESSAGES } from '../../src/static-pages/data/portfolioTranslations.js';

test('portfolio skills keep R&D central while separating hardware process automation', async () => {
  let source = await readFile(new URL('../../src/static-pages/js/index.js', import.meta.url), 'utf8');

  assert.match(source, /id: 'skills\/rnd-engineering'/);
  assert.match(source, /id: 'skills\/hardware-capture'/);
  assert.match(source, /key: 'agenticAi'/);
  assert.match(source, /details: tPortfolio\('skill\.agenticAi\.details'\)/);
  assert.match(source, /details: skill\.details/);
  assert.match(source, /let result = \['skills\/rnd-engineering'\];/);
  assert.doesNotMatch(source, /skills\/automation/);
});

test('portfolio file tree groups projects by primary domain', async () => {
  let source = await readFile(new URL('../../src/static-pages/js/index.js', import.meta.url), 'utf8');

  assert.match(source, /const PROJECT_TREE_GROUPS = \[/);
  assert.match(source, /id: 'agentic-ai'[\s\S]*'agent-portal'[\s\S]*'project-graph-mcp'[\s\S]*'symbiote-engine'/);
  assert.match(source, /const PROJECT_TREE_GROUP_PRIORITIES = Object\.freeze\(\{/);
  assert.match(source, /'agentic-ai': \[[\s\S]*'agent-portal'[\s\S]*'symbiote-workspace'[\s\S]*'symbiote-engine'[\s\S]*'project-graph-mcp'[\s\S]*'agent-pool-mcp'/);
  assert.match(source, /const orderedPortfolioProjects = orderProjectsForTree\(projects\);/);
  assert.match(source, /const portfolioTreeItems = createTreeItems\(orderedPortfolioProjects, orderedPortfolioProjects\);/);
  assert.match(source, /setNodePositions\(this\.canvas, orderedPortfolioProjects\);/);
  assert.match(source, /id: 'product-ui'[\s\S]*'symbiote-video-studio'[\s\S]*'megavisor'[\s\S]*'symbiote-ui'/);
  assert.match(source, /id: 'archive'[\s\S]*treeLabel: tPortfolio\('projectGroup\.archive\.label'\)[\s\S]*'symbiote-node'/);
  assert.match(source, /id: 'hardware-capture'[\s\S]*'autobox-v1'[\s\S]*'complexscan'[\s\S]*'boothbot'[\s\S]*'photopizza'/);
  assert.match(source, /treeLabel: tPortfolio\('projectGroup\.agenticAi\.label'\)/);
  assert.match(source, /treeLabel: tPortfolio\('projectGroup\.productUi\.label'\)/);
  assert.match(source, /treeLabel: tPortfolio\('projectGroup\.archive\.label'\)/);
  assert.match(source, /treeLabel: tPortfolio\('projectGroup\.hardware\.label'\)/);
  assert.match(source, /resourcePathSegment\(getProjectTreeGroupLabel\(getProjectTreeGroup\(project\)\)\)/);
  assert.match(source, /const TREE_STORAGE_KEY = `cv-portfolio-materials-tree-v4:\$\{portfolioLocalization\.locale\}`;/);
});

test('portfolio skill routes match the active skill identifiers', async () => {
  let root = new URL('../../src/static-pages/skills/', import.meta.url);

  await access(new URL('rnd-engineering/index.html.js', root));
  await access(new URL('hardware-capture/index.html.js', root));
  await assert.rejects(
    access(new URL('automation/index.html.js', root)),
    { code: 'ENOENT' }
  );
});

test('portfolio profile states full-stack work, native stack, and stack adaptation', () => {
  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.page.title'], /hardware/i);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.summary'], /Lead full-stack R&D engineer/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.summary'], /process automation/);
  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.summary'], /hardware/i);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.agenticAi.summary'], /MCP\/WebMCP/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.agenticAi.summary'], /RAG-style context retrieval/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.agenticAi.summary'], /structured execution state/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.agenticAi.summary'], /context compression/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.agenticAi.summary'], /model\/resource routing/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.agenticAi.summary'], /eval-style checks/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.agenticAi.summary'], /guardrails/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.agenticAi.summary'], /provider metadata/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /Current work centers/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /stack adaptation/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /GSM modems/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /AT-command control/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /agent-operable interfaces/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /context engineering/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /graph-based project understanding/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /model\/resource routing/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /observability/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /audit gates/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /\[Lifecycle Messaging Platform\]\(projects\/lifecycle-messaging-platform\/\?lang=en\)/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.statusDetails'], /Open to a new R&D \/ product engineering project/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.statusDetails'], /async-friendly format/);
  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.statusDetails'], /hardware/i);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /RND-PRO engineering team/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.details'], /Hardware and field automation are additional engineering depth/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.focusDetails'], /AI tooling, web\/platform engineering/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.focusDetails'], /bonus capability/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.workFormatDetails'], /Remote, written-first R&D \/ product engineering/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.workFormatDetails'], /inside an existing team, with a clear manager/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.achievement.rndProducts.details'], /Invented original product and technology lines/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.achievement.hardware.label'], /Physical prototypes/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.achievement.hardware.details'], /shipped products internationally/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.achievement.museumScanning.details'], /upper competitive level of its time/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.career.megavisor.details'], /capture-side R&D/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.career.hardware.details'], /original museum-grade 3D scanning technology/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.achievement.aiTooling.details'], /resource-aware orchestration/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.achievement.aiTooling.details'], /RAG-style retrieval/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.career.ai.details'], /human-in-the-loop control/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.career.ai.details'], /Agent Portal, Project Graph, Agent Pool/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.career.messaging.details'], /Confidential commercial platform/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.bio.details'], /RND-PRO engineering team/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.bio.details'], /server infrastructure/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.locationLabel'], /Location/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.locationValue'], /Buenos Aires, Argentina \(GMT-3\)/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.availabilityLabel'], /Time zones/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.availability'], /Available for other time zones/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.languagesLabel'], /Languages/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.languagesValue'], /not spoken/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.contactLabel'], /Contact/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.experienceLabel'], /Experience/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.experienceSummary'], /10\+ years in R&D, product engineering, and full-stack development/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.profile.onlineCv'], /Online CV/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.experience.rnd.label'], /R&D engineering experience/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.experience.rnd.details'], /physical systems when useful/);
  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.experience.rnd.details'], /and hardware\./);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.experience.programming.label'], /Programming \/ full-stack experience/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.experience.programming.details'], /JavaScript, Node\.js, Web\/PWA, and Web Components/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.experience.programming.details'], /PostgreSQL/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.experience.programming.details'], /including Python when needed/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.experience.programming.details'], /AT-command control/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skills.details'], /frontend\/backend\/runtime\/ops stacks including Python when needed/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skills.details'], /MCP\/tool use/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skills.details'], /Skill concentration/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skills.details'], /Agent Portal/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skills.details'], /GSM modem pools/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.agenticAi.details'], /context compression/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.rnd.details'], /release gates/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.productUi.details'], /admin panels/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.skill.hardwareCapture.details'], /physical prototypes/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.pdf.summaryDetails'], /custom AI tooling/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.en['portfolio.pdf.projectsTitle'], /Selected project evidence/);

  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.page.title'], /hardware|желез/i);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.summary'], /Ведущий full-stack R&D-инженер/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.summary'], /автоматизации процессов/);
  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.summary'], /hardware|желез/i);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skill.agenticAi.summary'], /MCP\/WebMCP/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skill.agenticAi.summary'], /RAG-style context retrieval/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skill.agenticAi.summary'], /сжатие контекста/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skill.agenticAi.summary'], /маршрутизация моделей\/ресурсов/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skill.agenticAi.summary'], /guardrails/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skill.agenticAi.summary'], /provider metadata/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /Текущий фокус/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /адаптации к стеку/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /GSM-модемы/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /AT-команды/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /agent-operable интерфейсы/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /context engineering/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /графовое понимание проекта/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /маршрутизация моделей\/ресурсов/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /observability/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /audit gates/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /\[Lifecycle Messaging Platform\]\(projects\/lifecycle-messaging-platform\/\?lang=ru\)/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.statusDetails'], /Открыт к новому R&D \/ product engineering проекту/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.statusDetails'], /async-friendly формате/);
  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.statusDetails'], /hardware|желез|аппаратн/i);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /RND-PRO engineering team/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.details'], /Hardware и полевая автоматизация остаются дополнительной инженерной глубиной/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.focusDetails'], /web\/platform engineering/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.focusDetails'], /не главный акцент поиска/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.workFormatDetails'], /письменно-ориентированная R&D/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.workFormatDetails'], /внутри существующей команды, с понятным руководителем/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.achievement.rndProducts.details'], /Придумывал собственные продуктовые и технологические линии/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.achievement.hardware.label'], /Физические прототипы/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.achievement.hardware.details'], /отправлял изделия за границу/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.achievement.museumScanning.details'], /верхней конкурентной планки своего времени/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.career.megavisor.details'], /R&D съёмочной части/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.career.hardware.details'], /авторской музейной технологии 3D-сканирования/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.achievement.aiTooling.details'], /resource-aware оркестрации/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.achievement.aiTooling.details'], /RAG-style retrieval/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.career.ai.details'], /human-in-the-loop контроль/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.career.ai.details'], /Agent Portal, Project Graph, Agent Pool/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.career.messaging.details'], /Конфиденциальная коммерческая платформа/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.bio.details'], /RND-PRO engineering team/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.bio.details'], /серверную инфраструктуру/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.locationLabel'], /Локация/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.locationValue'], /Buenos Aires, Argentina \(GMT-3\)/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.availabilityLabel'], /Часовые пояса/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.availability'], /других часовых поясах/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.languagesLabel'], /Языки/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.languagesValue'], /не разговорный/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.contactLabel'], /Контакт/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.experienceLabel'], /Опыт/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.experienceSummary'], /10\+ лет в R&D, продуктовой инженерии и full-stack разработке/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.profile.onlineCv'], /Онлайн CV/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.experience.rnd.label'], /R&D-инженерный опыт/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.experience.rnd.details'], /физических систем/);
  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.experience.rnd.details'], /железа/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.experience.programming.label'], /Программистский \/ full-stack опыт/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.experience.programming.details'], /Родной стек: JavaScript, Node\.js, Web\/PWA и Web Components/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.experience.programming.details'], /PostgreSQL/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.experience.programming.details'], /Python при необходимости/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.experience.programming.details'], /управлением через serial и AT-команды/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skills.details'], /frontend\/backend\/runtime\/ops-стекам, включая Python при необходимости/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skills.details'], /MCP\/tool use/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skills.details'], /Концентрация навыков/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skills.details'], /Agent Portal/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skills.details'], /GSM-модемные пулы/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skill.agenticAi.details'], /сжатие контекста/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skill.rnd.details'], /release gates/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skill.productUi.details'], /admin-панели/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.skill.hardwareCapture.details'], /физические прототипы/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.pdf.summaryDetails'], /кастомные ИИ-инструменты/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.ru['portfolio.pdf.projectsTitle'], /Избранные проектные подтверждения/);

  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.page.title'], /hardware/i);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.summary'], /Ingeniero full-stack líder de I\+D/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.summary'], /automatización de procesos/);
  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.summary'], /hardware/i);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skill.agenticAi.summary'], /MCP\/WebMCP/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skill.agenticAi.summary'], /RAG-style context retrieval/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skill.agenticAi.summary'], /compresión de contexto/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skill.agenticAi.summary'], /enrutamiento de modelos\/recursos/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skill.agenticAi.summary'], /guardrails/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skill.agenticAi.summary'], /provider metadata/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /La línea actual/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /adaptarme a stacks/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /módems GSM/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /comandos AT/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /interfaces operables por agentes/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /context engineering/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /comprensión de proyecto basada en grafos/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /enrutamiento de modelos\/recursos/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /observability/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /audit gates/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /\[Lifecycle Messaging Platform\]\(projects\/lifecycle-messaging-platform\/\?lang=es\)/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.statusDetails'], /Abierto a un nuevo proyecto/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.statusDetails'], /async-friendly/);
  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.statusDetails'], /hardware/i);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /RND-PRO engineering team/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.details'], /profundidad de ingeniería adicional/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.focusDetails'], /web\/platform engineering/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.focusDetails'], /no el centro de la búsqueda/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.workFormatDetails'], /Trabajo remoto y por escrito de I\+D/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.workFormatDetails'], /dentro de un equipo existente/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.achievement.rndProducts.details'], /Inventé líneas originales de producto y tecnología/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.achievement.hardware.label'], /Prototipos físicos/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.achievement.hardware.details'], /envié productos internacionalmente/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.achievement.museumScanning.details'], /nivel competitivo alto de su momento/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.career.megavisor.details'], /I\+D de captura/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.career.hardware.details'], /tecnología propia de escaneo 3D/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.achievement.aiTooling.details'], /orquestación consciente de recursos/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.achievement.aiTooling.details'], /RAG-style retrieval/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.career.ai.details'], /human-in-the-loop/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.career.ai.details'], /Agent Portal, Project Graph, Agent Pool/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.career.messaging.details'], /Plataforma comercial confidencial/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.bio.details'], /RND-PRO engineering team/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.bio.details'], /infraestructura de servidor/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.locationLabel'], /Ubicación/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.locationValue'], /Buenos Aires, Argentina \(GMT-3\)/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.availabilityLabel'], /Husos horarios/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.availability'], /otros husos horarios/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.languagesLabel'], /Idiomas/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.languagesValue'], /no conversacional/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.contactLabel'], /Contacto/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.experienceLabel'], /Experiencia/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.experienceSummary'], /10\+ años en I\+D, ingeniería de producto y desarrollo full-stack/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.profile.onlineCv'], /CV online/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.experience.rnd.label'], /Experiencia de ingeniería I\+D/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.experience.rnd.details'], /sistemas físicos/);
  assert.doesNotMatch(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.experience.rnd.details'], /y hardware\./);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.experience.programming.label'], /Experiencia de programación \/ full-stack/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.experience.programming.details'], /JavaScript, Node\.js, Web\/PWA y Web Components/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.experience.programming.details'], /PostgreSQL/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.experience.programming.details'], /incluido Python/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.experience.programming.details'], /comandos AT/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skills.details'], /stacks frontend\/backend\/runtime\/ops desconocidos incluido Python/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skills.details'], /MCP\/tool use/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skills.details'], /Concentración de habilidades/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skills.details'], /Agent Portal/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skills.details'], /pools de módems GSM/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skill.agenticAi.details'], /compresión de contexto/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skill.rnd.details'], /release gates/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skill.productUi.details'], /admin panels/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.skill.hardwareCapture.details'], /prototipos físicos/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.pdf.summaryDetails'], /herramientas de IA a medida/);
  assert.match(PORTFOLIO_LOCALE_MESSAGES.es['portfolio.pdf.projectsTitle'], /Evidencia de proyectos seleccionados/);
});

test('portfolio profile renders languages, contact, and separated experience sections', async () => {
  let source = await readFile(new URL('../../src/static-pages/js/index.js', import.meta.url), 'utf8');

  assert.doesNotMatch(source, /PORTFOLIO_PROFILE_AGE/);
  assert.match(source, /const PORTFOLIO_LINKEDIN_URL = 'https:\/\/www\.linkedin\.com\/in\/v-matiasevich\/';/);
  assert.match(source, /const PORTFOLIO_TELEGRAM_URL = 'https:\/\/t\.me\/text2code';/);
  assert.match(source, /title: tPortfolio\('profile\.statusTitle'\)/);
  assert.doesNotMatch(source, /profile\.factsTitle/);
  assert.match(source, /title: tPortfolio\('profile\.focusTitle'\)/);
  assert.match(source, /body: tPortfolio\('profile\.focusDetails'\)/);
  assert.match(source, /title: tPortfolio\('profile\.workFormatTitle'\)/);
  assert.match(source, /body: tPortfolio\('profile\.workFormatDetails'\)/);
  assert.match(source, /title: tPortfolio\('profile\.achievementsTitle'\)/);
  assert.match(source, /label: tPortfolio\('profile\.achievement\.hardware\.label'\)/);
  assert.match(source, /title: tPortfolio\('profile\.careerTitle'\)/);
  assert.match(source, /label: tPortfolio\('profile\.career\.megavisor\.label'\)/);
  assert.match(source, /const PORTFOLIO_ONLINE_CV_URL = 'https:\/\/MakerDrive\.github\.io\/cv-v-matiasevich\/';/);
  assert.match(source, /function getProfileOnlineCvUrl\(locale = portfolioLocalization\.locale\)/);
  assert.match(source, /\| --- \| --- \|/);
  assert.match(source, /tPortfolio\('profile\.locationLabel'\)/);
  assert.match(source, /tPortfolio\('profile\.locationValue'\)/);
  assert.match(source, /tPortfolio\('profile\.availabilityLabel'\)/);
  assert.match(source, /tPortfolio\('profile\.availability'\)/);
  assert.match(source, /tPortfolio\('profile\.languagesLabel'\)/);
  assert.match(source, /tPortfolio\('profile\.contactLabel'\)/);
  assert.match(source, /tPortfolio\('profile\.experienceLabel'\)/);
  assert.match(source, /tPortfolio\('profile\.experienceSummary'\)/);
  assert.match(source, /tPortfolio\('profile\.onlineCv'\)/);
  assert.match(source, /meta: getProfileMetaText\(\)/);
  assert.match(source, /title: tPortfolio\('experience\.title'\)/);
  assert.match(source, /label: tPortfolio\('experience\.rnd\.label'\)/);
  assert.match(source, /label: tPortfolio\('experience\.programming\.label'\)/);
  assert.match(source, /sections: getProfileSections\(\)/);
});
